services:
  user:
    cap_add:
    - NET_BIND_SERVICE
    cap_drop:
    - all
    command: /config/mockintosh.yml 'http://user'
    environment:
    - MOCKINTOSH_FORCE_PORT=80
    hostname: user
    image: testrio/mockintosh:latest
    ports:
    - 80
    read_only: true
    volumes:
    - .:/config
version: '3.3'
