services:
  carts:
    cap_add:
    - NET_BIND_SERVICE
    cap_drop:
    - all
    command: /config/mockintosh.yml 'http://carts'
    environment:
    - MOCKINTOSH_FORCE_PORT=80
    hostname: carts
    image: testrio/mockintosh:latest
    ports:
    - 80
    read_only: true
    volumes:
    - .:/config
  catalogue:
    cap_add:
    - NET_BIND_SERVICE
    cap_drop:
    - all
    command: /config/mockintosh.yml 'http://catalogue'
    environment:
    - MOCKINTOSH_FORCE_PORT=80
    hostname: catalogue
    image: testrio/mockintosh:latest
    ports:
    - 80
    read_only: true
    volumes:
    - .:/config
  front-end:
    cap_add:
    - NET_BIND_SERVICE
    cap_drop:
    - all
    command: /config/mockintosh.yml 'http://front-end'
    environment:
    - MOCKINTOSH_FORCE_PORT=80
    hostname: front-end
    image: testrio/mockintosh:latest
    ports:
    - 80
    read_only: true
    volumes:
    - .:/config
  payment:
    cap_add:
    - NET_BIND_SERVICE
    cap_drop:
    - all
    command: /config/mockintosh.yml 'http://payment'
    environment:
    - MOCKINTOSH_FORCE_PORT=80
    hostname: payment
    image: testrio/mockintosh:latest
    ports:
    - 80
    read_only: true
    volumes:
    - .:/config
  shipping:
    cap_add:
    - NET_BIND_SERVICE
    cap_drop:
    - all
    command: /config/mockintosh.yml 'http://shipping'
    environment:
    - MOCKINTOSH_FORCE_PORT=80
    hostname: shipping
    image: testrio/mockintosh:latest
    ports:
    - 80
    read_only: true
    volumes:
    - .:/config
  user:
    cap_add:
    - NET_BIND_SERVICE
    cap_drop:
    - all
    command: /config/mockintosh.yml 'http://user'
    environment:
    - MOCKINTOSH_FORCE_PORT=80
    hostname: user
    image: testrio/mockintosh:latest
    ports:
    - 80
    read_only: true
    volumes:
    - .:/config
version: '3.3'
