services:
  api:
    cap_add:
    - NET_BIND_SERVICE
    cap_drop:
    - all
    command: /config/mockintosh.yml 'http://api'
    environment:
    - MOCKINTOSH_FORCE_PORT=80
    hostname: api
    image: testrio/mockintosh:latest
    ports:
    - 80
    read_only: true
    volumes:
    - .:/config
  cache:
    cap_add:
    - NET_BIND_SERVICE
    cap_drop:
    - all
    command: /config/mockintosh.yml 'http://cache'
    environment:
    - MOCKINTOSH_FORCE_PORT=80
    hostname: cache
    image: testrio/mockintosh:latest
    ports:
    - 80
    read_only: true
    volumes:
    - .:/config
  currency:
    cap_add:
    - NET_BIND_SERVICE
    cap_drop:
    - all
    command: /config/mockintosh.yml 'http://currency'
    environment:
    - MOCKINTOSH_FORCE_PORT=80
    hostname: currency
    image: testrio/mockintosh:latest
    ports:
    - 80
    read_only: true
    volumes:
    - .:/config
  payments:
    cap_add:
    - NET_BIND_SERVICE
    cap_drop:
    - all
    command: /config/mockintosh.yml 'http://payments'
    environment:
    - MOCKINTOSH_FORCE_PORT=80
    hostname: payments
    image: testrio/mockintosh:latest
    ports:
    - 80
    read_only: true
    volumes:
    - .:/config
  web:
    cap_add:
    - NET_BIND_SERVICE
    cap_drop:
    - all
    command: /config/mockintosh.yml 'http://web'
    environment:
    - MOCKINTOSH_FORCE_PORT=80
    hostname: web
    image: testrio/mockintosh:latest
    ports:
    - 80
    read_only: true
    volumes:
    - .:/config
version: '3.3'
