version: "3.3"
services:
  up9-passive-tapper-web:
    image: gcr.io/up9-docker-hub/passive-tapper/develop:latest
    restart: always
    environment:
      WEB_SOCKET_PORT: "17123"
      APP_PORTS: 9090,80
    command:
      - /app/passive_tapper
      - -i
      - eth0
      - -verbose
    network_mode: service:web
    labels:
      com.up9.tapped: false
  up9-passive-tapper-api:
    image: gcr.io/up9-docker-hub/passive-tapper/develop:latest
    restart: always
    environment:
      WEB_SOCKET_PORT: "17123"
      APP_PORTS: 9090,80
    command:
      - /app/passive_tapper
      - -i
      - eth0
      - -verbose
    network_mode: service:api
    labels:
      com.up9.tapped: false
  up9-passive-tapper-cache:
    image: gcr.io/up9-docker-hub/passive-tapper/develop:latest
    restart: always
    environment:
      WEB_SOCKET_PORT: "17123"
      APP_PORTS: 9090,80
    command:
      - /app/passive_tapper
      - -i
      - eth0
      - -verbose
    network_mode: service:cache
    labels:
      com.up9.tapped: false
  up9-passive-tapper-payments:
    image: gcr.io/up9-docker-hub/passive-tapper/develop:latest
    restart: always
    environment:
      WEB_SOCKET_PORT: "17123"
      APP_PORTS: 9090,80
    command:
      - /app/passive_tapper
      - -i
      - eth0
      - -verbose
    network_mode: service:payments
    labels:
      com.up9.tapped: false
  up9-collector:
    image: gcr.io/up9-docker-hub/collector/develop:latest
    restart: always
    volumes:
      - /Users/alongir/.config/up9/tap/test1/collector.json:/opt/up9/localConfig.json
      - /var/run/docker.sock:/var/run/docker.sock
    env_file: /Users/alongir/.config/up9/tests/test1/credentials.env
    environment:
      MODE: local
      AGENT_NAME: local-alon@up9.com
      TRAFFIC_DUMPER_EXTERNAL_HOSTNAME: traffic.stg.testr.io
      UP9_ENV_SUFFIX: stg.testr.io
    labels:
      com.up9.tapped: false
    depends_on:
      &a1
      - web
      - api
      - cache
      - payments
  up9-auth-helper:
    image: gcr.io/up9-docker-hub/authentication-helper/develop:latest
    restart: always
    labels:
      com.up9.tapped: false
    depends_on: *a1
  up9-agent:
    image: gcr.io/up9-docker-hub/trcc-agent/develop:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      CONTAINER_ORCHESTRATION_SYSTEM: docker
      UP9_ENV_SUFFIX: stg.testr.io
      TEST_RUNNER_VERSION: develop:latest
      AGENT_NAME: local-alon@up9.com
      AGENT_ID: 936f6aed0fc55d2a171b67f6031a7188
      AUTH_HELPER_SERVER: up9-auth-helper
    env_file: /Users/alongir/.config/up9/tests/test1/credentials.env
    labels:
      com.up9.tapped: false
    depends_on: *a1
