package up9_autogenerated_tests

import (
    . "authentication"
    . "up9lib"
    assert "github.com/stretchr/testify/assert"
    testing "testing"
)

func TestGetCartsIdItems13(t *testing.T) {
    id := "57a98d98e4b00679b4a830b2"

    // GET http://carts/carts/{id}/items (endp 13)
    id := "57a98d98e4b00679b4a830b2"
    carts := GetHttpTarget(t, "TARGET_CARTS", new(Authentication))
    req := new(HttpRequest)
    resp := carts.Get(req, "/carts/" + id.(string) + "/items")
    assert.Equal(t, 200, resp.StatusCode())
}

func TestGetCartsIdMerge12(t *testing.T) {
    id := "57a98d98e4b00679b4a830b2"
    sessionId := "7w4TGI0pnIxn5TEFoHX6O2spPdXa3dut"

    // GET http://carts/carts/{id}/merge (endp 12)
    id := "57a98d98e4b00679b4a830b2"
    sessionId := "7w4TGI0pnIxn5TEFoHX6O2spPdXa3dut"
    carts := GetHttpTarget(t, "TARGET_CARTS", new(Authentication))
    req := new(HttpRequest)
    req.SetQueryString(map[string]interface{}{
        "sessionId": sessionId,
    })
    resp := carts.Get(req, "/carts/" + id.(string) + "/merge")
    assert.Equal(t, 202, resp.StatusCode())
}
