package up9_autogenerated_tests

import (
    . "authentication"
    . "up9lib"
    assert "github.com/stretchr/testify/assert"
    testing "testing"
)

func TestGetCatalogue10(t *testing.T) {
    size := "5"

    // GET http://catalogue/catalogue (endp 10)
    size := "5"
    catalogue := GetHttpTarget(t, "TARGET_CATALOGUE", new(Authentication))
    req := new(HttpRequest)
    req.SetQueryString(map[string]interface{}{
        "page": "1",
        "size": size,
        "tags": "",
    })
    resp := catalogue.Get(req, "/catalogue")
    assert.Equal(t, 200, resp.StatusCode())
}

func TestGetCatalogueSize09(t *testing.T) {
    // GET http://catalogue/catalogue/size (endp 9)
    catalogue := GetHttpTarget(t, "TARGET_CATALOGUE", new(Authentication))
    req := new(HttpRequest)
    req.SetQueryString(map[string]interface{}{
        "tags": "",
    })
    resp := catalogue.Get(req, "/catalogue/size")
    assert.Equal(t, 200, resp.StatusCode())
}

func TestGetTags11(t *testing.T) {
    // GET http://catalogue/tags (endp 11)
    catalogue := GetHttpTarget(t, "TARGET_CATALOGUE", new(Authentication))
    req := new(HttpRequest)
    resp := catalogue.Get(req, "/tags")
    assert.Equal(t, 200, resp.StatusCode())
}
