package up9_autogenerated_tests

import (
    . "authentication"
    . "up9lib"
    assert "github.com/stretchr/testify/assert"
    regexp "regexp"
    testing "testing"
)

func TestGet01(t *testing.T) {
    // GET http://front-end/ (endp 1)
    frontEnd := GetHttpTarget(t, "TARGET_FRONT_END", new(Authentication))
    req := new(HttpRequest)
    resp := frontEnd.Get(req, "/")
    assert.Contains(t, CssSelect(t, "div#hot div.box div.container div h2", resp), "Hot this week")
}

func TestGetParam26(t *testing.T) {
    // GET http://front-end/{param} (endp 26)
    param := "navbar.html"
    frontEnd := GetHttpTarget(t, "TARGET_FRONT_END", new(Authentication))
    req := new(HttpRequest)
    req.SetHeaders(map[string]interface{}{
        "x-requested-with": "XMLHttpRequest",
    })
    resp := frontEnd.Get(req, "/" + param)
    assert.Equal(t, 200, resp.StatusCode())
}

func TestGetBasketHtml59(t *testing.T) {
    // GET http://front-end/basket.html (endp 59)
    frontEnd := GetHttpTarget(t, "TARGET_FRONT_END", new(Authentication))
    req := new(HttpRequest)
    resp := frontEnd.Get(req, "/basket.html")
    assert.Equal(t, 200, resp.StatusCode())
    assert.Contains(t, CssSelect(t, "div#basket div.box form h1", resp), "Shopping cart")
}

func TestGetCart02(t *testing.T) {
    // GET http://front-end/cart (endp 2)
    frontEnd := GetHttpTarget(t, "TARGET_FRONT_END", new(Authentication))
    req := new(HttpRequest)
    req.SetHeaders(map[string]interface{}{
        "x-requested-with": "XMLHttpRequest",
    })
    resp := frontEnd.Get(req, "/cart")
    assert.Equal(t, 200, resp.StatusCode())
}

func TestDeleteCart43(t *testing.T) {
    // DELETE http://front-end/cart (endp 43)
    frontEnd := GetHttpTarget(t, "TARGET_FRONT_END", new(Authentication))
    req := new(HttpRequest)
    resp := frontEnd.Delete(req, "/cart")
    assert.Equal(t, 202, resp.StatusCode())
}

func TestPostCart61(t *testing.T) {
    // POST http://front-end/orders (endp 66)
    frontEnd := GetHttpTarget(t, "TARGET_FRONT_END", new(Authentication))
    req := new(HttpRequest)
    resp := frontEnd.Post(req, "/orders")
    assert.Equal(t, 201, resp.StatusCode())
    assert.Equal(t, "Glasgow", JsonPath(t, "$.address.city", resp.String()))
    id := JsonPath(t, "$.items[*].itemId", resp.String())

    // POST http://front-end/cart (endp 61)
    req2 := new(HttpRequest)
    req2.SetHeaders(map[string]interface{}{
        "content-type": "application/json",
    })
    req2.SetJsonBody("data/payload_for_endp_61.json", map[string]interface{}{
        "$.id": id,
    })
    resp2 := frontEnd.Post(req2, "/cart")
    assert.Equal(t, 201, resp2.StatusCode())
}

func TestGetCatalogue37(t *testing.T) {
    // GET http://front-end/catalogue (endp 37)
    size := "6"
    frontEnd := GetHttpTarget(t, "TARGET_FRONT_END", new(Authentication))
    req := new(HttpRequest)
    req.SetQueryString(map[string]interface{}{
        "page": "1",
        "size": size,
        "tags": "",
    })
    req.SetHeaders(map[string]interface{}{
        "x-requested-with": "XMLHttpRequest",
    })
    resp := frontEnd.Get(req, "/catalogue")
    assert.Equal(t, 200, resp.StatusCode())
}

func TestGetCatalogueId52(t *testing.T) {
    // GET http://front-end/catalogue (endp 4)
    size := "5"
    frontEnd := GetHttpTarget(t, "TARGET_FRONT_END", new(Authentication))
    req := new(HttpRequest)
    req.SetQueryString(map[string]interface{}{
        "page": "1",
        "size": size,
        "tags": "",
    })
    req.SetHeaders(map[string]interface{}{
        "x-requested-with": "XMLHttpRequest",
    })
    resp := frontEnd.Get(req, "/catalogue")
    assert.Regexp(t, regexp.MustCompile(".*Holy.*"), resp.String())
    id := JsonPath(t, "$[*].id", resp.String())

    // GET http://front-end/catalogue/{id} (endp 52)
    req2 := new(HttpRequest)
    req2.SetHeaders(map[string]interface{}{
        "x-requested-with": "XMLHttpRequest",
    })
    resp2 := frontEnd.Get(req2, "/catalogue/" + id)
    assert.Equal(t, 200, resp2.StatusCode())
}

func TestGetCatalogueSize03(t *testing.T) {
    // GET http://front-end/catalogue/size (endp 3)
    frontEnd := GetHttpTarget(t, "TARGET_FRONT_END", new(Authentication))
    req := new(HttpRequest)
    req.SetQueryString(map[string]interface{}{
        "tags": "",
    })
    req.SetHeaders(map[string]interface{}{
        "x-requested-with": "XMLHttpRequest",
    })
    resp := frontEnd.Get(req, "/catalogue/size")
    assert.Equal(t, 200, resp.StatusCode())
}

func TestGetCatalogueSize36(t *testing.T) {
    // GET http://front-end/catalogue/size (endp 36)
    frontEnd := GetHttpTarget(t, "TARGET_FRONT_END", new(Authentication))
    req := new(HttpRequest)
    req.SetQueryString(map[string]interface{}{
        "tags": "",
    })
    req.SetHeaders(map[string]interface{}{
        "x-requested-with": "XMLHttpRequest",
    })
    resp := frontEnd.Get(req, "/catalogue/size")
    assert.Equal(t, 200, resp.StatusCode())
}

func TestGetCategoryHtml34(t *testing.T) {
    // GET http://front-end/category.html (endp 34)
    frontEnd := GetHttpTarget(t, "TARGET_FRONT_END", new(Authentication))
    req := new(HttpRequest)
    resp := frontEnd.Get(req, "/category.html")
    assert.Contains(t, CssSelect(t, "div#content div.container div div.panel.panel-default.sidebar-menu div.panel-heading h3.panel-title", resp), "Filters ")
}

func TestGetCustomersCustomerid05(t *testing.T) {
    // GET http://front-end/customers/{customerId} (endp 5)
    customerId := "7w4TGI0pnIxn5TEFoHX6O2spPdXa3dut"
    frontEnd := GetHttpTarget(t, "TARGET_FRONT_END", new(Authentication))
    req := new(HttpRequest)
    req.SetHeaders(map[string]interface{}{
        "x-requested-with": "XMLHttpRequest",
    })
    resp := frontEnd.Get(req, "/customers/" + customerId)
    assert.Equal(t, "Name", JsonPath(t, "$.lastName", resp.String()))
}

func TestGetCustomersCustomerid30(t *testing.T) {
    // GET http://front-end/customers/{customerId} (endp 30)
    customerId := "7w4TGI0pnIxn5TEFoHX6O2spPdXa3dut"
    frontEnd := GetHttpTarget(t, "TARGET_FRONT_END", new(Authentication))
    req := new(HttpRequest)
    req.SetHeaders(map[string]interface{}{
        "x-requested-with": "XMLHttpRequest",
    })
    resp := frontEnd.Get(req, "/customers/" + customerId)
    assert.Equal(t, 200, resp.StatusCode())
}

func TestGetDetailHtml45(t *testing.T) {
    // POST http://front-end/orders (endp 66)
    frontEnd := GetHttpTarget(t, "TARGET_FRONT_END", new(Authentication))
    req := new(HttpRequest)
    resp := frontEnd.Post(req, "/orders")
    assert.Equal(t, 201, resp.StatusCode())
    assert.Equal(t, "Glasgow", JsonPath(t, "$.address.city", resp.String()))
    id := JsonPath(t, "$.items[*].itemId", resp.String())

    // GET http://front-end/detail.html (endp 45)
    req2 := new(HttpRequest)
    req2.SetQueryString(map[string]interface{}{
        "id": id,
    })
    resp2 := frontEnd.Get(req2, "/detail.html")
    assert.Contains(t, CssSelect(t, "div#content div.container div div.row.same-height-row div div.box.same-height h3", resp2), "You may also like these products")
}

func TestGetFooterHtml23(t *testing.T) {
    // GET http://front-end/footer.html (endp 23)
    frontEnd := GetHttpTarget(t, "TARGET_FRONT_END", new(Authentication))
    req := new(HttpRequest)
    req.SetHeaders(map[string]interface{}{
        "x-requested-with": "XMLHttpRequest",
    })
    resp := frontEnd.Get(req, "/footer.html")
    assert.Contains(t, CssSelect(t, "div#copyright div.container div p.pull-left a", resp), "Weaveworks")
}

func TestGetIndexHtml06(t *testing.T) {
    // GET http://front-end/index.html (endp 6)
    frontEnd := GetHttpTarget(t, "TARGET_FRONT_END", new(Authentication))
    req := new(HttpRequest)
    resp := frontEnd.Get(req, "/index.html")
    assert.Contains(t, CssSelect(t, "div#hot div.box div.container div h2", resp), "Hot this week")
}

// authentication-related test
func TestGetLogin25(t *testing.T) {
    // GET http://front-end/login (endp 25)
    frontEnd := GetHttpTarget(t, "TARGET_FRONT_END", new(DummyAuth))
    req := new(HttpRequest)
    req.SetHeaders(map[string]interface{}{
        "x-requested-with": "XMLHttpRequest",
    })
    resp := frontEnd.Get(req, "/login")
    assert.Contains(t, CssSelect(t, "p", resp), "Cookie is set")
}

func TestGetOrders07(t *testing.T) {
    // GET http://front-end/orders (endp 7)
    frontEnd := GetHttpTarget(t, "TARGET_FRONT_END", new(Authentication))
    req := new(HttpRequest)
    req.SetHeaders(map[string]interface{}{
        "x-requested-with": "XMLHttpRequest",
    })
    resp := frontEnd.Get(req, "/orders")
    assert.Equal(t, 201, resp.StatusCode())
}

func TestGetTags08(t *testing.T) {
    // GET http://front-end/tags (endp 8)
    frontEnd := GetHttpTarget(t, "TARGET_FRONT_END", new(Authentication))
    req := new(HttpRequest)
    req.SetHeaders(map[string]interface{}{
        "x-requested-with": "XMLHttpRequest",
    })
    resp := frontEnd.Get(req, "/tags")
    assert.Equal(t, 200, resp.StatusCode())
}

func TestGetTags38(t *testing.T) {
    // GET http://front-end/tags (endp 38)
    frontEnd := GetHttpTarget(t, "TARGET_FRONT_END", new(Authentication))
    req := new(HttpRequest)
    req.SetHeaders(map[string]interface{}{
        "x-requested-with": "XMLHttpRequest",
    })
    resp := frontEnd.Get(req, "/tags")
    assert.Equal(t, 200, resp.StatusCode())
}

func TestGetTopbarHtml27(t *testing.T) {
    // GET http://front-end/topbar.html (endp 27)
    frontEnd := GetHttpTarget(t, "TARGET_FRONT_END", new(Authentication))
    req := new(HttpRequest)
    req.SetHeaders(map[string]interface{}{
        "x-requested-with": "XMLHttpRequest",
    })
    resp := frontEnd.Get(req, "/topbar.html")
    assert.Contains(t, CssSelect(t, "div#top div.container div.offer a.btn.btn-success.btn-sm", resp), "Offer of the day")
}
