package up9_autogenerated_tests

import (
    . "authentication"
    . "up9lib"
    assert "github.com/stretchr/testify/assert"
    testing "testing"
)

func TestGetOrdersSearchCustomerid14(t *testing.T) {
    // GET http://orders/orders/search/customerId (endp 14)
    orders := GetHttpTarget(t, "TARGET_ORDERS", new(Authentication))
    req := new(HttpRequest)
    req.SetQueryString(map[string]interface{}{
        "custId": "undefined",
        "sort": "date",
    })
    resp := orders.Get(req, "/orders/search/customerId")
    assert.Equal(t, 200, resp.StatusCode())
}
