package up9_autogenerated_tests

import (
    . "authentication"
    . "up9lib"
    assert "github.com/stretchr/testify/assert"
    testing "testing"
)

func TestPostPaymentauth67(t *testing.T) {
    // POST http://payment/paymentAuth (endp 67)
    ccv := "958"
    country := "United Kingdom"
    expires := "08/19"
    longNum := "5544154011345918"
    number := "246"
    postcode := "G67 3DL"
    street := "Whitelees Road"
    payment := GetHttpTarget(t, "TARGET_PAYMENT", new(Authentication))
    req := new(HttpRequest)
    req.SetHeaders(map[string]interface{}{
        "accept": "application/json",
        "content-type": "application/json",
    })
    req.SetJsonBody("data/payload_for_endp_67.json", map[string]interface{}{
        "$.address.country": country,
        "$.address.number": number,
        "$.address.postcode": postcode,
        "$.address.street": street,
        "$.amount": RandomFloat(4.99, 104.979996),
        "$.card.ccv": ccv,
        "$.card.expires": expires,
        "$.card.longNum": longNum,
    })
    resp := payment.Post(req, "/paymentAuth")
    assert.Equal(t, 200, resp.StatusCode())
}
