package up9_autogenerated_tests

import (
    . "authentication"
    . "up9lib"
    assert "github.com/stretchr/testify/assert"
    testing "testing"
    uuid "github.com/google/uuid"
)

func TestPostShipping68(t *testing.T) {
    // POST http://shipping/shipping (endp 68)
    name := "57a98d98e4b00679b4a830b2"
    shipping := GetHttpTarget(t, "TARGET_SHIPPING", new(Authentication))
    req := new(HttpRequest)
    req.SetHeaders(map[string]interface{}{
        "accept": "application/json",
        "content-type": "application/json",
    })
    req.SetJsonBody("data/payload_for_endp_68.json", map[string]interface{}{
        "$.id": uuid.New().String(),
        "$.name": name,
    })
    resp := shipping.Post(req, "/shipping")
    assert.Equal(t, 201, resp.StatusCode())
}
