package up9_autogenerated_tests

import (
    . "authentication"
    . "up9lib"
    assert "github.com/stretchr/testify/assert"
    testing "testing"
)

func TestGetCustomersId15(t *testing.T) {
    id := "57a98d98e4b00679b4a830b2"

    // GET http://user/customers/{id} (endp 15)
    id := "57a98d98e4b00679b4a830b2"
    user := GetHttpTarget(t, "TARGET_USER", new(Authentication))
    req := new(HttpRequest)
    resp := user.Get(req, "/customers/" + id.(string))
    assert.Equal(t, 200, resp.StatusCode())
    assert.Equal(t, "Name", JsonPath(t, "$.lastName", resp.String()))
}

// authentication-related test
func TestGetLogin16(t *testing.T) {
    // GET http://user/login (endp 16)
    user := GetHttpTarget(t, "TARGET_USER", new(DummyAuth))
    req := new(HttpRequest)
    resp := user.Get(req, "/login")
    assert.Equal(t, 200, resp.StatusCode())
    assert.Equal(t, "Name", JsonPath(t, "$.user.lastName", resp.String()))
}
